Hi3Helper.sln
Hi3HelperGUI/Classes/Data/BlockData.cs
Hi3HelperGUI/Classes/Data/ScreenData.cs
Hi3HelperGUI/Classes/Data/ScreenInterop.cs
Hi3HelperGUI/Classes/GUI/BlockSection.cs
Hi3HelperGUI/Classes/GUI/CheckAvailableVersion.cs
Hi3HelperGUI/Classes/Preset/Classes/PresetConfigClasses.cs
Hi3HelperGUI/Classes/Preset/Classes/XMFDictionaryClasses.cs
Hi3HelperGUI/Hi3HelperGUI.csproj
Hi3HelperGUI/MainWindow.xaml
Hi3HelperGUI/config/appconfig.json
Hi3HelperGUI/config/fileconfig.json

This commit bring a support for Steam version of Honkai Impact 3 (basically have almost the same data with Global Version).
Also implement the initial Screen Resolution component for Settings Editor feature.

Steam version support and Initial Screen Resolution component

---

.gitignore
Hi3Helper.sln
Hi3HelperCore/Classes/Data/BlockData.cs
Hi3HelperCore/Classes/Data/ScreenData.cs
Hi3HelperCore/Classes/Data/ScreenInterop.cs
Hi3HelperCore/Classes/Data/Tools/ConverterTool.cs
Hi3HelperCore/Classes/Data/Tools/HttpClientTool.cs
Hi3HelperCore/Classes/Data/Tools/INIParserTool.cs
Hi3HelperCore/Classes/Data/UpdateData.cs
Hi3HelperCore/Classes/Data/XMFData.cs
Hi3HelperCore/Classes/Logger/ConsoleLogger.cs
Hi3HelperCore/Classes/Logger/DummyLogger.cs
Hi3HelperCore/Classes/Logger/ILogger.cs
Hi3HelperCore/Classes/Logger/Logger.cs
Hi3HelperCore/Classes/Preset/Classes/PresetConfigClasses.cs
Hi3HelperCore/Classes/Preset/Classes/XMFDictionaryClasses.cs
Hi3HelperCore/Classes/Preset/ConfigStore.cs
Hi3HelperCore/Hi3HelperCore.csproj
Hi3HelperGUI/Classes/GUI/BlockSection.cs
Hi3HelperGUI/Classes/GUI/CheckAvailableVersion.cs
Hi3HelperGUI/Classes/GUI/DownloadSection.cs
Hi3HelperGUI/Classes/GUI/UpdateSection.cs
Hi3HelperGUI/Classes/Preset/AppConfigLoader.cs
Hi3HelperGUI/Hi3HelperGUI.csproj
Hi3HelperGUI/MainWindow.xaml
Hi3HelperGUI/MainWindow.xaml.cs

This changes will be used for further development of this app and gives possibility to make a version for another platform in the future (cross-platform), like Android.

Separate some Methods to Hi3HelperCore project

---

Hi3HelperCore/Lang/zh-cn.json

This pull request is to update the Simplified Chinese translation in the launcher.
This translation may not be accurate (as it cannot be translated in real time against the launcher), but it is largely understandable for today's usage.
--- 
这个拉动请求是为了更新启动器中的简体中文翻译。
这个翻译可能并不准确（因为不能对启动器进行实时翻译），但对于当今的使用情况来说，它基本上是可以理解的。

Update  Chinese (Simplified) Translation

---

CollapseLauncher/Classes/BackgroundManagement/BackgroundManagement.cs
CollapseLauncher/Classes/CachesManagement/CachesCheck.cs
CollapseLauncher/Classes/CachesManagement/CachesUpdate.cs
CollapseLauncher/Classes/EventsManagement/EventsHandler.cs
CollapseLauncher/Classes/InstallManagement/GameConversionManagement.cs
CollapseLauncher/Classes/InstallManagement/InstallManagement.PatchExt.cs
CollapseLauncher/Classes/InstallManagement/InstallManagement.cs
CollapseLauncher/Classes/RepairManagement/DataCheck.cs
CollapseLauncher/Classes/RepairManagement/DataRepair.cs
CollapseLauncher/XAMLs/MainApp/MainPage.xaml.cs
CollapseLauncher/XAMLs/MainApp/Pages/Dialogs/InstallationConvert.xaml.cs
CollapseLauncher/XAMLs/MainApp/Pages/HomePage.xaml.cs
CollapseLauncher/XAMLs/MainApp/Pages/UpdatePage.xaml.cs
CollapseLauncher/XAMLs/Updater/Classes/Updater.cs
Hi3Helper.Core/Classes/Data/Tools/GenshinDispatchHelper/GenshinDispatchHelper.cs
Hi3Helper.Core/Classes/Shared/GameConversion/CheckIntegrity.cs
Hi3Helper.Core/Classes/Shared/GameConversion/SteamConversion.cs
Hi3Helper.Core/Classes/Shared/Region/ConfigV2Store.cs

As the title says, the launcher will be moved to new refactored ``Hi3Helper.Http``. The changes are supposed to fix issues related to this submodule, which is Data Downloading.
There are issues related:
- #30 - (by: @dfmjndm)
- #26 - (by: @muscularcandy67)
- #19 - (by: @muscularcandy67)
- #17 - (by: @muscularcandy67)

Refactor Hi3Helper.Http

---

Hi3Helper.Core/Lang/zh-cn.json

Hi! I've translated all the untranslated content up to October 16,
and after a cursory look, there should be no problems, so you can just merge!
Thank you for maintaining this launcher❤️!
---
hi！我已经将October 16为止的未翻译内容已经全部翻译，
粗略看了一下，应该没有什么问题，您可以直接进行合并！
辛苦您维护这个启动器❤️！
#14

Update translation of Simplified Chinese

---

Hi3Helper.Core/Lang/pt-pt.json

Correction of simple mistakes in the previous translation.
#50

[pt-PT] Correction of syntax

---

README.md

As the title says, this makes the README more readable and fixes lots of typos and sentence structure issues. 
Edit: Some planned changes and additions in the near or far future include a better documentation and project goal tracking(?).

Re-format README, fix typos, better structure

---

CONTRIBUTING.md
SECURITY.md

This is done to make progress on Community Standards insight.

Add Contributing and Security guidelines

---

CollapseLauncher/XAMLs/MainApp/MainPage.xaml.cs

Fix draggable area covers minimize button

---

CollapseLauncher/XAMLs/MainApp/MainPage.xaml

Optimize the display of NavigationView

---

CollapseLauncher/Assets/Presets/CommunityTools.json
CollapseLauncher/XAMLs/MainApp/Pages/HomePage.xaml
CollapseLauncher/XAMLs/MainApp/Pages/HomePage.xaml.cs
Hi3Helper.Core/Classes/Logger/Enum/LogType.cs
Hi3Helper.Core/Classes/Logger/LoggerBase.cs
Hi3Helper.Core/Lang/Locale/LangHomePage.cs
Hi3Helper.Core/Lang/en-us.json

+ Use Action Tag generator to generate actions in URL string for better expandability for other tools in the future.
+ Move the Community Tool button in the same Grid column to adjust its position automatically.
+ Move the UI's Texts to localization file

Community Toolkit Improvements

---

CollapseLauncher/Classes/InstallManagement/BaseClass/InstallManagerBase.cs

Attempt to fix full package detection that returned 0 even if the file was fully downloaded

Fix full package detection

---

CollapseLauncher/Classes/InstallManagement/BaseClass/InstallManagerBase.cs

Janky attempt to identify if either full zip or slices preload are available

Pre-load check

---

Hi3Helper.Core/Classes/Shared/Region/Config/LauncherConfig.cs
Hi3Helper.Core/Lang/Locale/LangMisc.cs
Hi3Helper.Core/Lang/en-us.json

Using my domain for now due to the emergency of the situation

Implement Cloudflare CDN

---

Hi3Helper.Core/Classes/Data/Tools/GenshinDispatchHelper/GenshinDispatchHelper.cs

Dispatch URL:
```
https://cngfdispatch.yuanshen.com/query_cur_region?version=CNRELWin3.8.0&lang=2&platform=3&binary=1&time=561&channel_id=1&sub_channel_id=1&account_type=1&dispatchSeed=9cff23dae5983f8d&key_id=4
```

Game repairing supports Genshin CN server

---

CollapseLauncher/Assets/Presets/CommunityTools.json

Add HI3 Community Tools

---

CollapseLauncher/Classes/GameManagement/GameSettings/Genshin/RegistryClass/GeneralData.cs
CollapseLauncher/Classes/GameManagement/GameSettings/Genshin/RegistryClass/GlobalPerfData.cs
CollapseLauncher/Classes/GameManagement/GameSettings/Genshin/RegistryClass/GraphicsData.cs
CollapseLauncher/Classes/GameManagement/GameSettings/Genshin/RegistryClass/ScreenManager.cs
CollapseLauncher/Classes/GameManagement/GameSettings/StarRail/RegistryClass/Model.cs
CollapseLauncher/Classes/GameManagement/GameSettings/StarRail/RegistryClass/PCResolution.cs
CollapseLauncher/Classes/GameManagement/GameSettings/Universal/RegistryClass/CollapseScreenSetting.cs
CollapseLauncher/XAMLs/MainApp/Pages/GameSettingsPage.Ext.cs
CollapseLauncher/XAMLs/MainApp/Pages/GameSettingsPage.xaml
CollapseLauncher/XAMLs/MainApp/Pages/GenshinGameSettingsPage.Ext.cs
CollapseLauncher/XAMLs/MainApp/Pages/GenshinGameSettingsPage.xaml
CollapseLauncher/XAMLs/MainApp/Pages/HomePage.xaml.cs
CollapseLauncher/XAMLs/MainApp/Pages/StarRailGameSettingsPage.Ext.cs
CollapseLauncher/XAMLs/MainApp/Pages/StarRailGameSettingsPage.xaml
Hi3Helper.Core/Lang/Locale/LangGameSettingsPage.cs
Hi3Helper.Core/Lang/Locale/LangStarRailGameSettingsPage.cs
Hi3Helper.Core/Lang/en-us.json

Following new updates
This also includes adding new option to enable Borderless Screen mode on all Games supported by Collapse, and some small code fixes.

Update for HSR and GI Game Settings classes

---

CollapseLauncher/Classes/RepairManagement/Honkai/Check.cs
CollapseLauncher/XAMLs/MainApp/Pages/HomePage.xaml
CollapseLauncher/XAMLs/MainApp/Pages/HomePage.xaml.cs
Hi3Helper.Core/Lang/Locale/LangDialogs.cs

Too many commits merged = conflicts

Attempt to fix main after neon-changes merge

---

CollapseLauncher/Classes/EventsManagement/EventsHandler.cs
CollapseLauncher/Program.cs
CollapseLauncher/XAMLs/MainApp/MainPage.xaml.cs

Reason: not have multiple log lines about squirrel not being able to update on debug builds

Disable Squirrel update on DEBUG builds

---

CollapseLauncher/XAMLs/MainApp/MainPage.xaml.cs

Add finishing touches for build-version-indicator started by @Cryotechnic

Complete Version Indicator 

---

CollapseLauncher/Classes/GameManagement/GameSettings/Genshin/RegistryClass/Enums/Enums.cs
CollapseLauncher/Classes/GameManagement/GameSettings/Genshin/RegistryClass/GlobalPerfData.cs
CollapseLauncher/Classes/GameManagement/GameSettings/Genshin/RegistryClass/GraphicsData.cs
CollapseLauncher/XAMLs/MainApp/Pages/GenshinGameSettingsPage.Ext.cs
CollapseLauncher/XAMLs/MainApp/Pages/GenshinGameSettingsPage.xaml

HoYoVerse added new render scale target so this is a PR to patch Collapse to support it.

Gi renderscale fixconcept

---

CollapseLauncher/XAMLs/MainApp/Pages/HomePage.xaml.cs

Tested on Genshin and Star Rail

Fix auto HDR

---

README.ja-jp.md
README.md

Japanese translated README.md

---

CollapseLauncher/XAMLs/MainApp/Pages/CachesPage.xaml.cs
CollapseLauncher/XAMLs/MainApp/Pages/GameSettingsPage.xaml.cs
CollapseLauncher/XAMLs/MainApp/Pages/GenshinGameSettingsPage.xaml.cs
CollapseLauncher/XAMLs/MainApp/Pages/HomePage.xaml.cs
CollapseLauncher/XAMLs/MainApp/Pages/RepairPage.xaml.cs
CollapseLauncher/XAMLs/MainApp/Pages/StarRailGameSettingsPage.xaml.cs

- Changed some checks from App.IsGameRunning to CurrentGameProperty.IsGameRunning to reflect other changes
This also fixes Discord Rich Presence not showing playing status

fix: Game Running status not detected

---

Hi3Helper.Core/Lang/zh_CN.json

Updated for Simplified Chinese

Implement SimpleDialog for Force Updating in Metered Connection

---

CollapseLauncher/Classes/GameManagement/GameVersion/BaseClass/GameVersionBase.cs
CollapseLauncher/Classes/InstallManagement/BaseClass/InstallManagerBase.cs
CollapseLauncher/Classes/InstallManagement/Genshin/GenshinInstall.cs
CollapseLauncher/Classes/InstallManagement/StarRail/StarRailInstall.cs
CollapseLauncher/Classes/Interfaces/Class/ProgressBase.cs
CollapseLauncher/Classes/RegionManagement/RegionClasses.cs
CollapseLauncher/Classes/RegionManagement/RegionManagement.cs
CollapseLauncher/Classes/RepairManagement/Genshin/Fetch.cs
CollapseLauncher/Classes/RepairManagement/StarRail/Fetch.cs
CollapseLauncher/XAMLs/MainApp/Pages/HomePage.xaml.cs
Hi3Helper.Core/Classes/Data/Tools/GenshinDispatchHelper/GenshinDispatchHelper.cs

[![Build-Canary](https://github.com/CollapseLauncher/Collapse/actions/workflows/build.yml/badge.svg?branch=bilibili-support)](https://github.com/CollapseLauncher/Collapse/actions/workflows/build.yml)
#279 
Checklist

Bilibili Region Support

---

CollapseLauncher/CollapseLauncher.csproj

Fix Win2D trimming for HDR calibration

---

CollapseLauncher/XAMLs/MainApp/TrayIcon.xaml
CollapseLauncher/XAMLs/MainApp/TrayIcon.xaml.cs

Correct some typo.
Also, `Visibility` property is not working in PopupMenu mode, use `IsEnabled` instead.

Update tray context menu everytime

---

CollapseLauncher/CollapseLauncher.csproj
CollapseLauncher/XAMLs/MainApp/MainPage.xaml.cs
CollapseLauncher/XAMLs/MainApp/Pages/Dialogs/KeyboardShortcuts.cs
CollapseLauncher/packages.lock.json
Hi3Helper.Core/Lang/Locale/LangKeyboardShortcuts.cs
Hi3Helper.Core/Lang/en_US.json

Hello!
Per @bagusnl request, I've added a shortcut that reloads the Home page.
It works as if the launcher was changing to the same region. The default key is F5 and can't be changed.
Please let me know if any improvement is needed!

Add a keyboard shortcut that reloads the Home page

---

CollapseLauncher/CollapseLauncher.csproj

- **[Fix]** Hotfix for HSR 1.6.0 repair/cache mechanism

Preview 1.72.13 Release

---

CollapseLauncher/Classes/Interfaces/Class/ProgressBase.cs
CollapseLauncher/XAMLs/MainApp/Pages/CachesPage.xaml.cs
CollapseLauncher/XAMLs/MainApp/Pages/RepairPage.xaml.cs

Discussed in Discord.
Also https://github.com/CollapseLauncher/Collapse/commit/df65109fab76f3b3f77b60e74a578bef80618105#commitcomment-136007124

Avoid another infinity number on repair progress percentage

---

CollapseLauncher/Classes/GameManagement/GameSettings/StarRail/RegistryClass/LocalAudioLanguage.cs
CollapseLauncher/Classes/InstallManagement/StarRail/StarRailInstall.cs
CollapseLauncher/Classes/Interfaces/Class/ProgressBase.cs
CollapseLauncher/Classes/RepairManagement/Genshin/Repair.cs
CollapseLauncher/Classes/RepairManagement/Honkai/Repair.cs
CollapseLauncher/Classes/RepairManagement/StarRail/Repair.cs
CollapseLauncher/CollapseLauncher.csproj
CollapseLauncher/Program.cs
CollapseLauncher/XAMLs/MainApp/Pages/CachesPage.xaml.cs
CollapseLauncher/XAMLs/MainApp/Pages/RepairPage.xaml.cs
CollapseLauncher/XAMLs/MainApp/Pages/StarRailGameSettingsPage.Ext.cs
Hi3Helper.Core/Classes/Preset/Classes/PresetConfigV2.cs
appveyor-preview.yaml
appveyor-stable.yaml

- **[Fix]** Fixed error on game repair caused by wrongly assigned value
- **[Fix]** Fixed Honkai: Star Rail installation issue where the wrong VO files is applied
- **[Fix]** Fixed memory leaks on HTTP submodule
- **[Imp]** Improve initialization time for HTTP submodule

Stable 1.72.15 Hotfix Release

---

README.fr-fr.md
README.id-id.md
README.ja-jp.md
README.md
README.pt-pt.md
README.ru-ru.md

Really just for testing AppVeyor/SignPath but who's counting?
:urunfast:

Sync preview to main

---

CollapseLauncher/Assets/Presets/CommunityTools.json
CollapseLauncher/Classes/Interfaces/Class/CommunityToolsProperty.cs
CollapseLauncher/XAMLs/MainApp/Pages/HomePage.xaml.cs

Community tools for different zones

---

InstallerProp/DeployInstaller-Preview.iss
InstallerProp/DeployInstaller-Stable.iss
InstallerProp/DeployInstaller-preview-AppVeyor.iss
InstallerProp/DeployInstaller-stable-AppVeyor.iss

why in the world did i added a comma there ?

Push InnoSetup script fix to preview

---

CollapseLauncher/Classes/EventsManagement/EventsHandler.cs
CollapseLauncher/Classes/GameManagement/GameSettings/Genshin/RegistryClass/ScreenManager.cs
CollapseLauncher/Classes/GameManagement/GameSettings/Genshin/RegistryClass/VisibleBackground.cs
CollapseLauncher/Classes/GameManagement/GameSettings/Genshin/Settings.cs
CollapseLauncher/Classes/GameManagement/GameSettings/StarRail/RegistryClass/Model.cs
CollapseLauncher/Classes/InstallManagement/BaseClass/InstallManagerBase.cs
CollapseLauncher/Classes/Properties/ArgumentParser.cs
CollapseLauncher/CollapseLauncher.csproj
CollapseLauncher/XAMLs/MainApp/Pages/Dialogs/SimpleDialogs.cs
CollapseLauncher/XAMLs/MainApp/Pages/GameSettingsPage.xaml.cs
CollapseLauncher/XAMLs/MainApp/Pages/GenshinGameSettingsPage.Ext.cs
CollapseLauncher/XAMLs/MainApp/Pages/StarRailGameSettingsPage.xaml.cs
Hi3Helper.Core/Lang/Locale/LangUnhandledExceptionPage.cs
Hi3Helper.Core/Lang/en_US.json

- **[Fix]** Fixed "Change Release" and "Force Update" mechanism, by @gablm 
- **[Fix]** Fixed Honkai: Star Rail showing A/B test warning on region load, by @Cryotechnic 
- This message is now only shown when opening HSR Game Settings page
- **[Fix]** Fixed crashing issue with SevenZipExtractor submodule, by @neon-nyan 
- **[Imp]** Implement Borderless Settings for Genshin Impact, by @bagusnl 
- Note: Collapse Borderless settings will have priority over GI's implementation.

Stable Hotfix 1.72.17 Release

---

CollapseLauncher/Classes/GameManagement/GameSettings/Genshin/RegistryClass/Enums/Enums.cs
CollapseLauncher/Classes/GameManagement/GameSettings/Genshin/RegistryClass/GlobalPerfData.cs
CollapseLauncher/Classes/GameManagement/GameSettings/Genshin/RegistryClass/GraphicsData.cs
CollapseLauncher/XAMLs/MainApp/Pages/GenshinGameSettingsPage.Ext.cs
CollapseLauncher/XAMLs/MainApp/Pages/GenshinGameSettingsPage.xaml
Hi3Helper.Core/Lang/Locale/LangGenshinGameSettingsPage.cs
Hi3Helper.Core/Lang/en_US.json

Add a corresponding checkbox to Genshin Impact settings page.

Support GI `Dynamic Character Resolution`

---

CollapseLauncher/XAMLs/MainApp/MainPage.xaml.cs
CollapseLauncher/XAMLs/MainApp/MainWindow.xaml.cs
CollapseLauncher/XAMLs/StartUp/StartupLanguageSelect.xaml.cs

Fix non-client area related issues, like drag area and system buttons.

Recalculate non-client area size after changing window size

---

CollapseLauncher/XAMLs/MainApp/MainPage.xaml.cs

[URL Protocol] Fix Discord Rich Presence not updating.

---

CollapseLauncher/Classes/CachesManagement/Honkai/Update.cs
CollapseLauncher/Classes/CachesManagement/StarRail/Update.cs
CollapseLauncher/Classes/FileMigrationProcess/Events.cs
CollapseLauncher/Classes/FileMigrationProcess/FileMigrationProcess.cs
CollapseLauncher/Classes/FileMigrationProcess/IO.cs
CollapseLauncher/Classes/InstallManagement/BaseClass/InstallManagerBase.cs
CollapseLauncher/Classes/InstallManagement/GameConversionManagement.cs
CollapseLauncher/Classes/Interfaces/Class/ProgressBase.cs
CollapseLauncher/Classes/RegionManagement/RegionManagement.cs
CollapseLauncher/Classes/RepairManagement/BSDiff.cs
CollapseLauncher/CollapseLauncher.csproj
Hi3Helper.Core/Classes/Shared/Region/LauncherConfig.cs
Hi3Helper.Core/Lang/Locale/LangMisc.cs
Hi3Helper.Core/Lang/en_US.json
Hi3Helper.Core/Lang/es_419.json
Hi3Helper.Core/Lang/zh_CN.json

- **[Fix]** Properly fix TimeSpan overflow, by @neon-nyan 
- **[Fix]** Corruption on Game Migration, by @neon-nyan 
- **[Fix]** Region loading related crashes, by @gablm 
- Fixes crash when cancelling
- Fixes Instant Region Change not working if the the first region load is cancelled
- **[New]** Coding CDN for Mainland China users, by @shatyuka 
-  **[Fix]** Exception on high download thread count, by @neon-nyan 
- **[Doc]** Deprecate Bitbucket mirror, by @bagusnl
- This due to the not so good GC implementation on Bitbucket causing CDN downtime whenever repo size touches 4GB
- **[Loc]** Localization sync from Transifex, by localizers <3
Template:
**[New]**
**[Imp]**
**[Fix]**
**[Loc]**
**[Doc]**

Preview 1.80.4 Hotfix Release

---

CollapseLauncher/Classes/GameManagement/GameVersion/BaseClass/GameVersionBase.cs
CollapseLauncher/Classes/Helper/LauncherApiLoader/HoYoPlay/HoYoPlayLauncherApiLoader.cs
Hi3Helper.Core/Lang/es_419.json
Hi3Helper.Core/Lang/id_ID.json
Hi3Helper.Core/Lang/ja_JP.json

- **[Fix]** Crashing while downloading Hi3 Preload, by @neon-nyan 
- **[Fix]** Crashing when opening social media buttons on HYP API, by @neon-nyan 
<details>
```
**[New]**
**[Imp]**
**[Fix]**
**[Loc]**
**[Doc]**
```
</details>

Preview 1.80.7 Hotfix Release

---

CollapseLauncher/Classes/Helper/WindowUtility.cs
CollapseLauncher/Classes/InstallManagement/BaseClass/InstallManagerBase.cs
CollapseLauncher/Classes/RepairManagement/Honkai/Check.cs
CollapseLauncher/Classes/RepairManagement/Honkai/HonkaiRepair.cs
CollapseLauncher/CollapseLauncher.csproj
Hi3Helper.Core/Classes/Shared/Region/LauncherConfig.cs
Hi3Helper.Core/Lang/fr_FR.json
README.md

- **[Fix]** Black top border on Windows 10, by @shatyuka 
- **[Fix]** Delta patch for Hi3 not applying due to Blocks.xmf added into the assets list, by @bagusnl 
- **[Fix]** Blocks and BlocksMeta keep reappearing in Hi3 Repair, by @neon-nyan 
- **[Imp]** Disable "Region Change Warning" for new users, by @bagusnl 
- This also auto-enables "Instant Region Change" as well
<details>
```
**[New]**
**[Imp]**
**[Fix]**
**[Loc]**
**[Doc]**
```
</details>
Close #472

Preview 1.80.8 Hotfix Release

---

CollapseLauncher/Classes/Extension/UIElementExtensions.cs
CollapseLauncher/CollapseLauncher.csproj
README.md

- **[Fix]** Crashing on launch on certain system due to value casting failure on shadow, by @neon-nyan 
- Thanks Microsoft.
<details>
```
**[New]**
**[Imp]**
**[Fix]**
**[Loc]**
**[Doc]**
```
</details>
fix #495

Preview 1.80.11 Emergency Hotfix Release

---

CollapseLauncher/Classes/Extension/UIElementExtensions.cs
CollapseLauncher/CollapseLauncher.csproj
README.md

- **[Fix]** Crashing on launch on certain system due to value casting failure on shadow, by @neon-nyan 
- Thanks Microsoft.
- **[Imp]** Sign ZstdNet and Sophon library for public releases, by @bagusnl 
<details>
```
**[New]**
**[Imp]**
**[Fix]**
**[Loc]**
**[Doc]**
```
</details>
fix #495

Stable 1.80.11 Emergency Hotfix

---

CollapseLauncher/Classes/DiscordPresence/DiscordPresenceManager.cs
CollapseLauncher/Classes/GameManagement/GameSettings/StarRail/RegistryClass/Model.cs
CollapseLauncher/Classes/GameManagement/GameVersion/StarRail/VersionCheck.cs
CollapseLauncher/Classes/Helper/Metadata/PresetConfig.cs
CollapseLauncher/Classes/InstallManagement/BaseClass/InstallManagerBase.cs
CollapseLauncher/Classes/RepairManagement/StarRail/Check.cs
CollapseLauncher/Classes/RepairManagement/StarRail/Fetch.cs
CollapseLauncher/Classes/ShortcutCreator/SteamShortcut.cs
CollapseLauncher/CollapseLauncher.csproj
CollapseLauncher/Program.cs
CollapseLauncher/XAMLs/MainApp/Pages/Dialogs/SimpleDialogs.cs
CollapseLauncher/XAMLs/MainApp/Pages/GameSettingsPages/StarRailGameSettingsPage.Ext.cs
CollapseLauncher/XAMLs/MainApp/Pages/GameSettingsPages/StarRailGameSettingsPage.xaml
CollapseLauncher/XAMLs/Theme/CustomControls/CommunityToolkit.Labs/DataTable/DataTable.cs
Hi3Helper.Core/Classes/Data/InvokeProp.cs
Hi3Helper.Core/Lang/Locale/LangStarRailGameSettingsPage.cs
Hi3Helper.Core/Lang/en_US.json
Hi3Helper.Core/Lang/ja_JP.json

- **[Fix]** Threading exception on certain UI components, causing the launcher to crash, by @shatyuka 
- **[Fix]** Sophon Installer crashed due to invalid type of Language String to Locale Code converter, by @neon-nyan 
- **[Fix]** Honkai: Star Rail Game Repair and Cache Update issues, by @bagusnl and @neon-nyan 
- Adding fallback method to lookup values in Honkai: Star Rail gateway API if the metadata KVP is not updated/unmatched
- Updating metadata's Key-Value pairs.
- Adding debug information for the Gateway API parser under ``Debug`` build
- Check for End-Of-File on the buffer
- Fix the location of certain patch-marked files under Persistent Folder
- Fix FileNotFound error on certain file marked under Persistent but found under StreamingAssets by hardlinking the file
- **[Imp]** Add …

Preview 1.80.12 Hotfix Release

---

CollapseLauncher/Classes/DiscordPresence/DiscordPresenceManager.cs
CollapseLauncher/Classes/GameManagement/GameSettings/StarRail/RegistryClass/Model.cs
CollapseLauncher/Classes/GameManagement/GameVersion/StarRail/VersionCheck.cs
CollapseLauncher/Classes/Helper/Metadata/PresetConfig.cs
CollapseLauncher/Classes/InstallManagement/BaseClass/InstallManagerBase.cs
CollapseLauncher/Classes/RepairManagement/StarRail/Check.cs
CollapseLauncher/Classes/RepairManagement/StarRail/Fetch.cs
CollapseLauncher/Classes/ShortcutCreator/SteamShortcut.cs
CollapseLauncher/CollapseLauncher.csproj
CollapseLauncher/Program.cs
CollapseLauncher/XAMLs/MainApp/Pages/Dialogs/SimpleDialogs.cs
CollapseLauncher/XAMLs/MainApp/Pages/GameSettingsPages/StarRailGameSettingsPage.Ext.cs
CollapseLauncher/XAMLs/MainApp/Pages/GameSettingsPages/StarRailGameSettingsPage.xaml
CollapseLauncher/XAMLs/Theme/CustomControls/CommunityToolkit.Labs/DataTable/DataTable.cs
Hi3Helper.Core/Classes/Data/InvokeProp.cs
Hi3Helper.Core/Lang/Locale/LangStarRailGameSettingsPage.cs
Hi3Helper.Core/Lang/en_US.json
Hi3Helper.Core/Lang/ja_JP.json

- **[Fix]** Threading exception on certain UI components, causing the launcher to crash, by @shatyuka 
- **[Fix]** Sophon Installer crashed due to invalid type of Language String to Locale Code converter, by @neon-nyan 
- **[Fix]** Honkai: Star Rail Game Repair and Cache Update issues, by @bagusnl and @neon-nyan 
- Adding fallback method to lookup values in Honkai: Star Rail gateway API if the metadata KVP is not updated/unmatched
- Updating metadata's Key-Value pairs.
- Adding debug information for the Gateway API parser under ``Debug`` build
- Check for End-Of-File on the buffer
- Fix the location of certain patch-marked files under Persistent Folder
- Fix FileNotFound error on certain file marked under Persistent but found under StreamingAssets by hardlinking the file
- **[Imp]** Add …

Stable 1.80.12 Hotfix Release

---

CollapseLauncher/Classes/InstallManagement/Zenless/ZenlessInstall.cs
README.md

- Fixes Collapse's inability to uninstall Zenless Zone Zero
Yeah, it is literally 1 line lmao but I'm bored so `¯\_(ツ)_/¯`
- Updates README.md for Zenless Zone Zero's features
Issue screenshot:
- Overall Status: Done
- Commits: Done
- Synced to base (Collapse: main): Yes
- Build status: OK
- Crashing: Yes
- Bug found caused by PR: #511 
<details>
mb what are these for?
```
**[New]**
**[Imp]**
**[Fix]**
**[Loc]**
**[Doc]**
```
</details>

Fixed Inability to uninstall ZZZ + Update to README.md for ZZZ

---

CollapseLauncher/Classes/Helper/StreamUtility.cs
CollapseLauncher/Classes/InstallManagement/BaseClass/InstallManagerBase.cs
CollapseLauncher/Classes/InstallManagement/GameConversionManagement.cs
CollapseLauncher/Classes/Interfaces/Class/ProgressBase.cs
CollapseLauncher/Classes/Interfaces/Class/Structs.cs
CollapseLauncher/Classes/RegionManagement/FallbackCDNUtil.cs
CollapseLauncher/Classes/RepairManagement/BSDiff.cs
CollapseLauncher/Classes/RepairManagement/Genshin/Fetch.cs
CollapseLauncher/Classes/RepairManagement/StarRail/Check.cs
CollapseLauncher/CollapseLauncher.csproj
CollapseLauncher/XAMLs/MainApp/Pages/Dialogs/SimpleDialogs.cs
CollapseLauncher/XAMLs/Updater/Classes/Updater.cs
CollapseLauncher/XAMLs/Updater/UpdaterWindow.xaml.cs
Hi3Helper.Core/Lang/Locale/LangUpdatePage.cs
Hi3Helper.Core/Lang/en_US.json
README.md

- **[Fix]** ``NullReferenceException`` crash caused by null ``voice_packs`` property, by @neon-nyan
- **[Fix]** Some migration dialog still provides install choices, by @neon-nyan
- **[Fix]** TimeSpan overflow + Number to Percentage and TimeSpan converter refactor, by @neon-nyan and @bagusnl
- **[Fix]** Minor Audio Selection UI bug, by @neon-nyan
- **[Fix]** More ``SharingViolation`` exceptions on ``InstallManagerBase``, by @neon-nyan
- **[Fix]** ``DirectoryNotFoundException`` on HSR's Game Repair -> ``RemoveHashMarkFile()`` method, by @neon-nyan
- **[Fix]** Relative URL for the Velopack packages getting cut-off, by @neon-nyan
<details>
```
**[New]**
**[Imp]**
**[Fix]**
**[Loc]**
**[Doc]**
```
</details>

Preview 1.82.10 Hotfix

---

.github/workflows/build.yml
.github/workflows/qodana-scan-pr.yml
.github/workflows/qodana-scan.yml
.github/workflows/vt-scan-releases.yml
CollapseLauncher/Classes/GameManagement/GamePlaytime/Playtime.cs
CollapseLauncher/Classes/InstallManagement/Base/InstallManagerBase.cs
CollapseLauncher/Classes/Interfaces/Class/ProgressBase.cs
CollapseLauncher/Classes/RepairManagement/Genshin/Check.cs
CollapseLauncher/Classes/RepairManagement/Genshin/Fetch.cs
CollapseLauncher/CollapseLauncher.csproj
Hi3Helper.Core/Lang/ja_JP.json
README.md

- **[Fix]** Launcher crashing when the main game thread unexpectedly closes, by @neon-nyan 
- **[Fix]** Taskbar progress not reset after game install/update, by @shatyuka 
- **[Fix]** Ensures temporary files availability, by @neon-nyan 
- **[Fix]** 7z COMException errors, by @neon-nyan 
- **[Fix]** Genshin's repair missing a few files, by @neon-nyan 
<details>
```
**[New]**
**[Imp]**
**[Fix]**
**[Loc]**
**[Doc]**
```
</details>

Stable 1.82.18 Hotfix

---

appveyor.yml

{Describe/list your goal for the PR here}
- Overall Status : Done/In Progress/Stalled/Cancelled
- Commits : Done/In Progress/Stalled/Cancelled
- Synced to base (Collapse:main) : Yes/Not yet
- Build status : OK/Crashing/Build Errors
- Crashing : Yes/No
- Bug found caused by PR : {int}
<details>
```
**[New]**
**[Imp]**
**[Fix]**
**[Loc]**
**[Doc]**
```
</details>

[CI][AppVeyor] Fix build issue

---

CollapseLauncher/Classes/InstallManagement/Base/InstallManagerBase.cs
CollapseLauncher/Classes/Interfaces/Class/Structs.cs
CollapseLauncher/XAMLs/MainApp/Pages/HomePage.GameManagement.cs
CollapseLauncher/XAMLs/MainApp/Pages/HomePage.xaml

Switch to the globe icon when downloading, otherwise it's the hard disk icon.

Dynamic installation status icon

---

CollapseLauncher/Classes/Extension/UIElementExtensions.cs
CollapseLauncher/Classes/Helper/HighlightableControlProperty.cs
CollapseLauncher/XAMLs/MainApp/Pages/SettingsPage.xaml
CollapseLauncher/XAMLs/MainApp/Pages/SettingsPage.xaml.cs
CollapseLauncher/XAMLs/MainApp/ValueConverters.cs
Hi3Helper.Core/Lang/Locale/LangSettingsPage.cs
Hi3Helper.Core/Lang/en_US.json

Add ability to do a search (string matching, not fuzzy) on collapse settings page
[2025-04-02 20-41-07.webm](https://github.com/user-attachments/assets/48cd5ed5-3d46-4bbc-84e5-9ddceddd7749)
closes #709 
- Crashing : Yes
- Bug found caused by PR : 0

[Feat] Search on App Settings Page

---

CollapseLauncher/Classes/FileMigrationProcess/FileMigrationProcess.cs
CollapseLauncher/Classes/FileMigrationProcess/FileMigrationProcessRef.cs
CollapseLauncher/Classes/FileMigrationProcess/Statics.cs
CollapseLauncher/Classes/FileMigrationProcess/UIBuilder.cs
CollapseLauncher/Classes/Helper/Background/Loaders/MediaPlayerLoader.cs
CollapseLauncher/Classes/Helper/Hash.StringAndBytes.cs
CollapseLauncher/Classes/Helper/Metadata/DataCooker.cs
CollapseLauncher/Classes/Helper/StreamUtility/CopyToStream.cs
CollapseLauncher/Classes/InstallManagement/Base/InstallManagerBase.PkgVersion.cs
CollapseLauncher/Classes/InstallManagement/Base/InstallManagerBase.SophonPatch.cs
CollapseLauncher/Classes/InstallManagement/Genshin/GenshinInstall.PkgVersion.cs
CollapseLauncher/Classes/InstallManagement/Genshin/GenshinInstall.cs
CollapseLauncher/Classes/Interfaces/Class/ProgressBase.cs
CollapseLauncher/Classes/Interfaces/Class/Structs.cs
CollapseLauncher/Classes/RegistryMonitor/RegistryMonitor.cs
CollapseLauncher/Classes/RepairManagement/Genshin/Check.cs
CollapseLauncher/Classes/RepairManagement/Genshin/Fetch.Persistent.cs
CollapseLauncher/Classes/RepairManagement/Genshin/Fetch.cs
CollapseLauncher/Classes/RepairManagement/Genshin/GenshinRepair.cs
CollapseLauncher/Classes/RepairManagement/Genshin/Repair.cs
CollapseLauncher/CollapseLauncher.csproj
CollapseLauncher/XAMLs/MainApp/Pages/FileCleanupPage.xaml.cs
Hi3Helper.Core/Classes/Logger/LoggerBase.cs

- **[Fix]** SharingViolation errors while installing/updating games with Sophon mode (eg. Genshin Impact and Zenless Zone Zero), by @neon-nyan
- **[Imp]** Streamline submodule branches to main for Hi3Helper.EncTool, Hi3Helper.Http and Hi3Helper.Sophon for easier maintainability, by @neon-nyan
- **[Imp+Fix]** Rewriting the whole Genshin Impact's Game Repair pipelines to match game in-game download behavior, by @neon-nyan.
This fixes most bugs, including some NotFound error, misplaced files and duplicate files due to the code still runs in how Genshin's in-game download behaves prior < 5.x
- **[Fix]** ``FileMigrationProcess`` pipelines, by @neon-nyan 
- Fix where the migration might remove unwanted non-game files.
- Fix where some old empty folders aren't getting removed.
- Fix …

Stable 1.82.24 Hotfix

---

CONTRIBUTING.md
CollapseLauncher/Classes/Extension/UIElementExtensions.cs
CollapseLauncher/Classes/FileMigrationProcess/FileMigrationProcess.cs
CollapseLauncher/Classes/FileMigrationProcess/FileMigrationProcessRef.cs
CollapseLauncher/Classes/FileMigrationProcess/Statics.cs
CollapseLauncher/Classes/FileMigrationProcess/UIBuilder.cs
CollapseLauncher/Classes/Helper/Background/Loaders/MediaPlayerLoader.cs
CollapseLauncher/Classes/Helper/Hash.StringAndBytes.cs
CollapseLauncher/Classes/Helper/HttpClientBuilder.cs
CollapseLauncher/Classes/Helper/Metadata/DataCooker.cs
CollapseLauncher/Classes/Helper/StreamUtility/CopyToStream.cs
CollapseLauncher/Classes/InstallManagement/Base/InstallManagerBase.PkgVersion.cs
CollapseLauncher/Classes/InstallManagement/Base/InstallManagerBase.SophonPatch.cs
CollapseLauncher/Classes/InstallManagement/Genshin/GenshinInstall.PkgVersion.cs
CollapseLauncher/Classes/InstallManagement/Genshin/GenshinInstall.cs
CollapseLauncher/Classes/Interfaces/Class/ProgressBase.cs
CollapseLauncher/Classes/Interfaces/Class/Structs.cs
CollapseLauncher/Classes/RegistryMonitor/RegistryMonitor.cs
CollapseLauncher/Classes/RepairManagement/Genshin/Check.cs
CollapseLauncher/Classes/RepairManagement/Genshin/Fetch.Persistent.cs
CollapseLauncher/Classes/RepairManagement/Genshin/Fetch.cs
CollapseLauncher/Classes/RepairManagement/Genshin/GenshinRepair.cs
CollapseLauncher/Classes/RepairManagement/Genshin/Repair.cs
CollapseLauncher/CollapseLauncher.csproj
CollapseLauncher/XAMLs/MainApp/Pages/FileCleanupPage.xaml.cs
CollapseLauncher/XAMLs/MainApp/Pages/SettingsPage.xaml
CollapseLauncher/XAMLs/MainApp/Pages/SettingsPage.xaml.cs
Hi3Helper.Core/Classes/Logger/LoggerBase.cs
README.md

- **[Fix]** SharingViolation errors while installing/updating games with Sophon mode (eg. Genshin Impact and Zenless Zone Zero), by @neon-nyan
- **[Imp]** Streamline submodule branches to main for Hi3Helper.EncTool, Hi3Helper.Http and Hi3Helper.Sophon for easier maintainability, by @neon-nyan
- **[Imp+Fix]** Rewriting the whole Genshin Impact's Game Repair pipelines to match game in-game download behavior, by @neon-nyan.
This fixes most bugs, including some NotFound error, misplaced files and duplicate files due to the code still runs in how Genshin's in-game download behaves prior < 5.x
- **[Fix]** Binding issues causing lags on SettingsPage's initial load, by @neon-nyan 
- **[Fix]** ``FileMigrationProcess`` pipelines, by @neon-nyan 
- Fix where the migration might remove unwanted …

Preview 1.83.2 Hotfix

---

CollapseLauncher/CollapseLauncher.csproj

- **[Fix]** Fix webp dlls missing from build, by @bagusnl 
<details>
```
**[New]**
**[Imp]**
**[Fix]**
**[Loc]**
**[Doc]**
```
</details>

[Hotfix of a hotfix] Stable 1.82.28 Release
