CollapseLauncher/Collapse

Hi3Helper.Core/Lang/en.json
This PR directly addresses #62 by changing the keyword to `shortly` from `momentarily` as well as removing a redundant sentence when the user is running a `Preview` release (the build is being tested so we don't need to say that there could be issues in the build as it is inherently assumed from the fact that the build is being tested).
If this PR gets merged, we'll need to close #62 as it is redundant.
=> [fix] Removed redundant keywords

CollapseLauncher/XAMLs/Updater/UpdaterWindow.xaml.cs
This PR partially addresses #67 by adjusting the following:
- Adds logging to let the user know that the application is not running under admin
- Kills the application after user presses a key in console window
- Implement some sort of GUI element to allow the user to restart with admin if they do not have Console enabled
OR
- Implement auto-restart if the application detects incorrect permission levels set
- Update README/wiki if the user encounters this error during development, with how to fix it
=> [feat] close app if not admin

CollapseLauncher/Classes/GameManagement/GameSettings/Genshin/RegistryClass/GeneralData.cs, CollapseLauncher/Classes/GameManagement/GameSettings/Genshin/RegistryClass/GlobalPerfData.cs, CollapseLauncher/Classes/GameManagement/GameSettings/Genshin/RegistryClass/GraphicsData.cs, CollapseLauncher/Classes/GameManagement/GameSettings/Genshin/RegistryClass/ScreenManager.cs, CollapseLauncher/Classes/GameManagement/GameSettings/Honkai/RegistryClass/PersonalAudioSetting.cs, CollapseLauncher/Classes/GameManagement/GameSettings/Honkai/RegistryClass/PersonalAudioSettingVolume.cs, CollapseLauncher/Classes/GameManagement/GameSettings/Honkai/RegistryClass/PersonalGraphicsSettingV2.cs, CollapseLauncher/Classes/GameManagement/GameSettings/Honkai/RegistryClass/ScreenSettingData.cs, CollapseLauncher/Classes/GameManagement/GameSettings/StarRail/RegistryClass/BGMVolume.cs, CollapseLauncher/Classes/GameManagement/GameSettings/StarRail/RegistryClass/LocalAudioLanguage.cs, CollapseLauncher/Classes/GameManagement/GameSettings/StarRail/RegistryClass/LocalTextLanguage.cs, CollapseLauncher/Classes/GameManagement/GameSettings/StarRail/RegistryClass/MasterVolume.cs, CollapseLauncher/Classes/GameManagement/GameSettings/StarRail/RegistryClass/Model.cs, CollapseLauncher/Classes/GameManagement/GameSettings/StarRail/RegistryClass/PCResolution.cs, CollapseLauncher/Classes/GameManagement/GameSettings/StarRail/RegistryClass/SFXVolume.cs, CollapseLauncher/Classes/GameManagement/GameSettings/StarRail/RegistryClass/VOVolume.cs, CollapseLauncher/Classes/GameManagement/GameSettings/Universal/RegistryClass/CollapseScreenSetting.cs, CollapseLauncher/Classes/GameManagement/GameSettings/Universal/RegistryClass/CustomArgs.cs, CollapseLauncher/XAMLs/MainApp/Pages/Dialogs/SimpleDialogs.cs, CollapseLauncher/XAMLs/MainApp/Pages/GameSettingsPage.xaml, CollapseLauncher/XAMLs/MainApp/Pages/GenshinGameSettingsPage.xaml, CollapseLauncher/XAMLs/MainApp/Pages/GenshinGameSettingsPage.xaml.cs, CollapseLauncher/XAMLs/MainApp/Pages/SettingsPage.xaml, CollapseLauncher/XAMLs/MainApp/Pages/StarRailGameSettingsPage.xaml, Hi3Helper.Core/Lang/Locale/LangMisc.cs, Hi3Helper.Core/Lang/en-us.json
- Fixed GI GameSettings: Gamma NumberBox appearance
- Added debug logger to Hi3 Settings and Collapse ScreenSettings
- Added missing exception catch on HI3 GameSettings
- Corrected debug loggers
- Fixed GI GameSettings RegistryWatcher not getting unsubscribed
- Adjusted `Install Game` button as `Install/Locate Game` (closes #150)
- Adjusted drop down height for big language selectors
- Adjusted margins on Game Settings page for HI3 and GI
- Changed Community Tool `Cancel` button for executable tools as `Open Download Page` following its actual behavior
- Fixed Gamma slider not updated when Gamma NumberBox is entered
- Fixed crashing when Gamma NumberBox is cleared
=> Some general improvements 

CollapseLauncher/Classes/Properties/InnerLauncherConfig.cs, CollapseLauncher/Classes/RegistryMonitor/RegistryMonitor.cs, CollapseLauncher/XAMLs/MainApp/Pages/GameSettingsPage.xaml.cs, CollapseLauncher/XAMLs/MainApp/Pages/GenshinGameSettingsPage.xaml.cs, CollapseLauncher/XAMLs/MainApp/Pages/HomePage.xaml.cs, CollapseLauncher/XAMLs/MainApp/Pages/SettingsPage.xaml, CollapseLauncher/XAMLs/MainApp/Pages/SettingsPage.xaml.cs, CollapseLauncher/XAMLs/MainApp/Pages/StarRailGameSettingsPage.xaml.cs, Hi3Helper.Core/Classes/DiscordPresence/DiscordPresenceManager.cs, Hi3Helper.Core/Classes/Shared/Region/Config/LauncherConfig.cs, Hi3Helper.Core/Lang/Locale/LangMisc.cs, Hi3Helper.Core/Lang/Locale/LangSettingsPage.cs, Hi3Helper.Core/Lang/en-us.json
- Move around some parts to make settings page a little bit more compact
- Hide some settings that depends on other
- [New] Add toggle to include Game logs inside Collapse Logs
- [New] Add contributors list button
- Localize `Region:` string
- [New] Add Collapse version and branch string to SmallText
- Add debug lines for RegistryMonitor
- Change operator for Launcher Metadata Update to only update when local stamp is older than remote
=> App Settings and Discord RPC Improvements

CollapseLauncher/Classes/InstallManagement/BaseClass/InstallManagerBase.cs, CollapseLauncher/Classes/InstallManagement/Genshin/GenshinInstall.cs, CollapseLauncher/Classes/InstallManagement/Honkai/HonkaiInstall.cs, CollapseLauncher/Classes/InstallManagement/StarRail/StarRailInstall.cs
making the entire function from the older try of this method into one beeg method.
Old reference: https://github.com/bagusnl/Collapse/blob/8296c077a1c7ea4730f38a3b657cb39cfec7a6e0/CollapseLauncher/Classes/InstallManagement/BaseClass/InstallManagerBase.cs#L398-L726
With the help of @Arikatsu, @muscularcandy67, and @Cryotechnic 
Resolve #141
=> Rewrite GameUninstall Method

CollapseLauncher/Classes/GameManagement/GameSettings/Genshin/RegistryClass/Enums/Enums.cs, CollapseLauncher/Classes/GameManagement/GameSettings/Genshin/RegistryClass/GeneralData.cs, CollapseLauncher/Classes/GameManagement/GameSettings/Genshin/RegistryClass/GlobalPerfData.cs, CollapseLauncher/Classes/GameManagement/GameSettings/Genshin/RegistryClass/GraphicsData.cs, CollapseLauncher/Classes/GameManagement/GameVersion/BaseClass/GameVersionBase.cs, CollapseLauncher/Classes/InstallManagement/BaseClass/InstallManagerBase.cs, CollapseLauncher/Classes/Interfaces/Class/ProgressBase.cs, CollapseLauncher/Classes/RepairManagement/Genshin/Check.cs, CollapseLauncher/Classes/RepairManagement/Genshin/Fetch.cs, CollapseLauncher/Classes/RepairManagement/Genshin/GenshinRepair.cs, CollapseLauncher/CollapseLauncher.csproj, CollapseLauncher/XAMLs/MainApp/Pages/Dialogs/SimpleDialogs.cs, CollapseLauncher/XAMLs/MainApp/Pages/GenshinGameSettingsPage.Ext.cs, CollapseLauncher/XAMLs/MainApp/Pages/GenshinGameSettingsPage.xaml, CollapseLauncher/XAMLs/MainApp/Pages/HomePage.xaml.cs, CollapseLauncher/XAMLs/MainApp/ValueConverters.cs, Hi3Helper.Core/Lang/Locale/LangGenshinGameSettingsPage.cs, Hi3Helper.Core/Lang/en-us.json, README.md
Following the update from GI 4.0
Changes:
- Item sorting is back to 3.7 version
- Adjusted mtr and url default values
- **New Settings:** DisableTeamPageBackground
- **New Settings:** Global Illumination
> Note: This setting will be ignored on unsupported specs
- New debug logging: dumps the entire json to multiple lines now :FuHuaEyes:
TODO:
~~Check Global Illumination toggle location~~
```
Adds Global Illumination on PlayStation® and will automatically be in effect after the Version update.
Adds Global Illumination on PC devices with a Discrete Graphics Card with a VRAM of 4 GB or more. Travelers may enable it via Settings > Graphics.
```
=> Genshin Game Settings update

CollapseLauncher/Assets/Presets/CommunityTools.json
Add battle chronicle websites to community tools for Honkai 3rd, Genshin Impact, and Honkai: Star Rail.
=> Add battle chronicle to community tools

CollapseLauncher/XAMLs/MainApp/Pages/HomePage.xaml.cs
Removes a typo ("s [x] seconds" => "s [x]")
Changes how the time played is displayed in the log ([m s] => [h m s])
=> [Playtime] Fix log message

CollapseLauncher/Classes/RegionManagement/RegionClasses.cs, CollapseLauncher/Classes/RegionManagement/RegionManagement.cs, CollapseLauncher/XAMLs/MainApp/Pages/HomePage.xaml, CollapseLauncher/XAMLs/MainApp/Pages/HomePage.xaml.cs
Make use of the `links` and `other_links` fields, and add link buttons to popup panel, especially for Chinese version.
<details>
<summary>social media icon JSON here</summary>
```json
{
"icon_id": "605077bbd90ba600951cd0e0",
"img": "https://webstatic.mihoyo.com/upload/operation_location/2021/03/16/40247bcc1f0092a7883949aade6619ac_3149808684055343336.png",
"tittle": "启动器常见问题FAQ",
"url": "https://bbs.mihoyo.com/ys/article/4004423",
"qr_img": "",
"qr_desc": "",
"img_hover": "https://webstatic.mihoyo.com/upload/operation_location/2021/03/16/021147ecf6824c3328d6c89b9c1b17e6_3771842119503074595.png",
"other_links": [
{
"title": "启动器意见集中反馈",
"url": "https://bbs.mihoyo.com/ys/article/5780277"
}
],
"title": "启动器常见问题FAQ",
"icon_link": "https://www.miyoushe.com/ys/article/39655595",
"links": [
{ …
```
=> Add links to social media popup panel

CollapseLauncher/Classes/InstallManagement/BaseClass/InstallManagerBase.cs, Hi3Helper.Core/Classes/Data/Tools/SteamTool.cs
This should fix any error related while trying to get steam path without throwing any exception.
=> [Fix] Return null when Steam path is not found

CollapseLauncher/Classes/EventsManagement/EventsHandler.cs, CollapseLauncher/XAMLs/MainApp/Pages/Dialogs/SimpleDialogs.cs, CollapseLauncher/XAMLs/MainApp/Pages/SettingsPage.xaml.cs, Hi3Helper.Core/Lang/Locale/LangDialogs.cs, Hi3Helper.Core/Lang/en_US.json, Hi3Helper.Core/Lang/zh_CN.json
[![Build-Canary](https://github.com/CollapseLauncher/Collapse/actions/workflows/build.yml/badge.svg?branch=metered-network)](https://github.com/CollapseLauncher/Collapse/actions/workflows/build.yml)
#286 
Behavior:
- On automated update check (every 15 minutes), skip the check if network is unavailable or set as metered.
- On forced update check (pressing Check for Update button in Settings page), shows warning dialog when metered connection is detected.
=> Add metered network for update

CollapseLauncher/Classes/GameManagement/GameSettings/Genshin/RegistryClass/Enums/Enums.cs, CollapseLauncher/Classes/GameManagement/GameSettings/Genshin/RegistryClass/GeneralData.cs, CollapseLauncher/Classes/GameManagement/GameSettings/Genshin/RegistryClass/GlobalPerfData.cs, CollapseLauncher/Classes/GameManagement/GameSettings/Genshin/RegistryClass/GraphicsData.cs, CollapseLauncher/XAMLs/MainApp/Pages/GenshinGameSettingsPage.Ext.cs, CollapseLauncher/XAMLs/MainApp/Pages/GenshinGameSettingsPage.xaml
Fix inconsistency with in-game settings.
Loading mechanism:
First try to load `globalPerfData`, and the current graphics quality option is saved in `saveItems` entryType 18. Then patch the selected graphics quality preset using entries in `saveItems`.
If `globalPerfData` does not exist (older versions), try to import it from `graphicsData`. May not be needed, but it's done anyway.
|  graphicsData   | globalPerfData  |
|  ----  | ----  |
| currentVolatielGrade  | saveItems entryType 18 |
| customVolatileGrades  | saveItems (-1 to zero-based) |
| volatileVersion  | portedVersion |
GlobalPerfData will now be used as the data source for the UI.
Also change the relevant enums to zero-based.
globalPerfData, High graphics quality, Antialiasing changed to SMAA
```json
{
"saveItems":[
{ …
```
=> Load Genshin graphics settings from ``globalPerfData``

CollapseLauncher/App.xaml, CollapseLauncher/CollapseLauncher.csproj, CollapseLauncher/packages.lock.json
Force `ShouldConstrainToRootBounds` to True using `Microsoft.Xaml.Behaviors`.
=> Workaround for ComboBox acrylic background

CollapseLauncher/App.xaml, CollapseLauncher/XAMLs/MainApp/MainWindow.xaml, CollapseLauncher/XAMLs/MainApp/MainWindow.xaml.cs, Hi3Helper.Core/Classes/Data/InvokeProp.cs
Remove the "ReunionCaptionControlsWindow" window to hide the control buttons.
Fix #311
=> Allow minimizing main window from taskbar

CollapseLauncher/Classes/Properties/InnerLauncherConfig.cs, CollapseLauncher/XAMLs/MainApp/MainWindow.xaml.cs, Hi3Helper.Core/Classes/Data/InvokeProp.cs
Windows App SDK 1.4 introduces a new issue. Double-clicking on the title bar will maximize the window, ignoring `IsMaximizable = false`.
Temporary workaround: register the WndProc hook to filter out the WM_SYSCOMMAND SC_MAXIMIZE message.
https://github.com/microsoft/microsoft-ui-xaml/issues/8666
=> Workaround for window maximize issue

CollapseLauncher/XAMLs/MainApp/Pages/HomePage.xaml, CollapseLauncher/XAMLs/MainApp/Pages/HomePage.xaml.cs
- Regard pips pager as a part of carousel
- Open image links only if left mouse button is pressed
Also found a tiny memory leak caused by `CancellationTokenSource`. It probably doesn't need fixing at this point.
=> Carousel adjustments

Hi3Helper.Core/Classes/Data/InvokeProp.cs, Hi3Helper.Core/Classes/Logger/Type/LoggerConsole.cs
Get the **real** console handle rather than the redirected handle returned by `GetStdHandle`, especially for Rider.
[GetStdHandle Remarks](https://learn.microsoft.com/en-us/windows/console/getstdhandle#remarks)
=> Set console output to the newly allocated console

CollapseLauncher/XAMLs/MainApp/MainWindow.xaml.cs, CollapseLauncher/XAMLs/MainApp/Pages/HomePage.xaml.cs, CollapseLauncher/XAMLs/MainApp/TrayIcon.xaml.cs, Hi3Helper.Core/Classes/Data/InvokeProp.cs
Converge operations to `WM_SYSCOMMAND` and `WM_SHOWWINDOW` to prevent missing some events.
~Edit: `WM_SIZE` and `WM_SHOWWINDOW` now~
Edit: reverted
Move the "MinimizeToTray" function to WndProc to fix the issue that minimizing a window from the taskbar does not minimize to the tray.
=> Auto stop carousel when main window is hidden

CollapseLauncher/Classes/InstallManagement/BaseClass/InstallManagerBase.cs
```
[Warn]  Failed while deleting file: D:\Games\CollapseLauncher\GICN\Genshin Impact Game\4ac3bc6fa573a0c57f5c096cc883aa5b_6304194074839243264.zip. Skipping!
System.IO.IOException: The process cannot access the file 'D:\Games\CollapseLauncher\GICN\Genshin Impact Game\4ac3bc6fa573a0c57f5c096cc883aa5b_6304194074839243264.zip' because it is being used by another process.
at System.IO.FileSystem.DeleteFile(String fullPath)
at System.IO.FileInfo.Delete()
at CollapseLauncher.InstallManager.GameInstallPackage.DeleteFile(Int32 count)
```
=> Dispose the stream before deleting install package

.gitmodules, ClearCache.bat, CollapseLauncher.sln, CollapseLauncher/CollapseLauncher.csproj, CollapseLauncher/XAMLs/MainApp/MainPage.xaml.cs, CollapseLauncher/XAMLs/Updater/Classes/Updater.cs, CollapseLauncher/packages.lock.json, InnoSetupHelper/InnoSetupHelper.csproj, InnoSetupHelper/InnoSetupLogUpdate.cs
This PR includes a change for updating the "Inno Setup Log"'s ``unins000.dat`` file, which is a manifest to list all the files to be removed on uninstalling the app.
Currently due to the nature of Collapse using Squirrel as its Update module and Inno Setup as its Installer for both Stable and Preview builds, all the updated files related with Collapse doesn't get registered in the ``unins000.dat`` file and making the uninstallation incomplete.
This PR also adding another submodule [**InnoSetupLogParser**](https://github.com/CollapseLauncher/InnoSetupLogParser/tree/main), which is a parser and modification tool for ``unins000.dat`` file. This submodule was initially created by [**preseverence**](https://github.com/preseverence/isulr) and has been modified to work on both Collapse and …
=> Update Inno Setup Log file after update

CollapseLauncher/packages.lock.json, Hi3Helper.Core/packages.lock.json
- **[Fix]** Fixed Double Empty issue on SevenZipExtractor that caused full crash
- **[Fix]** Fixed missing `subChanneID` and `channeID` required on `config.ini` file
- This fix HSR `Distribution Error` when launching the game #350
- **[Fix]** Fixed Collapse not uninstalled correctly due to missing entries on `InnoSetup log files`
- **[Fix]** Fixed HI3 7.2 `CGMetadata` repair stating `NotFound` error
- **[Fix]** Fixed `PropVariant` issue with `SevenZipExtractor` submodule
- **[Imp]** Use the new `CollapseMetadata V2` on HI3 for smaller fetch and faster repair
- **[Imp]** Update SharpHDiffPatch submodule
- **[Imp]** Implement `plugin` API to fetch games hotfixes automatically (thanks @shatyuka !)
- **[Imp]** Add warning for HSR GameSettings for those who got the new Settings mechanics
- The …
=> Preview 1.72.14 Pre-release Hotfix 

CollapseLauncher/Classes/Properties/AppActivation.cs, CollapseLauncher/Classes/Properties/ArgumentParser.cs
- Registers collapse:// as a URL protocol for Collapse
- collapse://open -g 0 -r 1 == CollapseLauncher.exe open -g 0 -r 1
- The protocol can be used through Win + R, .url files and web browsers
- Only "tray" and "open" can be used, mainly for prevention of things like:
\<a href="collapse://movesteam">One Billion Free Primogems here!\</a>
- Fixes most "private" command line arguments not working.
- As in #360, commands are always added to the root command, the previous implementation of adding arguments to the root command stopped working. This PR fixes this by converting them in commands. 
> Part of the process to implement #358 (2/3)
=> URL Protocol support

Hi3Helper.Core/Lang/de_DE.json, Hi3Helper.Core/Lang/es_419.json, Hi3Helper.Core/Lang/ja_JP.json, Hi3Helper.Core/Lang/ko_KR.json, Hi3Helper.Core/Lang/pt_PT.json, Hi3Helper.Core/Lang/ru_RU.json, Hi3Helper.Core/Lang/th_TH.json, Hi3Helper.Core/Lang/vi_VN.json, Hi3Helper.Core/Lang/zh_CN.json, Hi3Helper.Core/Lang/zh_TW.json, README.md, appveyor.yml
https://github.com/CollapseLauncher/Collapse/compare/CL-v1.73.0-pre...main
- **[New]** Open Collapse straight to specified region using command argument (thanks @gablm !)
- Now you can launch Collapse straight to your specified region (optionally also launch the game) directly using command line arguments!
- Note: You don't need to close your current Collapse process and it will redirect the command to already running instance! (Assuming you did not enable Multi instance in the settings)
- Usage : 
CollapseLauncher open [options]
- Options:
-g, --game <game> (REQUIRED)  Game number/name
e.g. 0 or "Honkai Impact 3rd"
-r, --region <region>         Region number/name
e.g. For Genshin Impact, 0 or "Global" would load the Global region for the game
-p, --play                    Start Game …
=> Preview 1.73.1 Release

CollapseLauncher/Classes/Properties/ArgumentParser.cs
For some reason, a CommandLine Command Handler tries to match the Option name with the Handler parameters name?
Thanks Microsoft!
This has been broken since at least 1.72.11 from my limited testing, maybe even earlier.
Because of this, forcing update is currently changing Preview to Stable release and Stable can't change to Preview back. 
Edit: Actually since 1.72.4
=> Fix "Change Release" and "Force Update"

CollapseLauncher/Classes/GameManagement/GameSettings/Universal/RegistryClass/CollapseScreenSetting.cs, CollapseLauncher/XAMLs/MainApp/Pages/GameSettingsPage.Ext.cs, CollapseLauncher/XAMLs/MainApp/Pages/GameSettingsPage.xaml, CollapseLauncher/XAMLs/MainApp/Pages/GenshinGameSettingsPage.Ext.cs, CollapseLauncher/XAMLs/MainApp/Pages/GenshinGameSettingsPage.xaml, CollapseLauncher/XAMLs/MainApp/Pages/HomePage.xaml.cs, CollapseLauncher/XAMLs/MainApp/Pages/StarRailGameSettingsPage.Ext.cs, CollapseLauncher/XAMLs/MainApp/Pages/StarRailGameSettingsPage.xaml, Hi3Helper.Core/Lang/Locale/LangGameSettingsPage.cs, Hi3Helper.Core/Lang/Locale/LangStarRailGameSettingsPage.cs, Hi3Helper.Core/Lang/en_US.json
This PR brings the "Resizable Window" which enables the Game Window to be resizable. This feature could only work on Windowed mode (not including borderless).
This feature works by using Win32 functions by manipulating the game window's ``GWL_STYLE`` flag.
https://learn.microsoft.com/en-us/windows/win32/winmsg/window-styles
"Use Custom Resolution" mode can only be used with "Resizable Window" enabled. If the "Resizable Window" is disabled, the checkbox for "Use Custom Resolution" will be disabled.
https://github.com/CollapseLauncher/Collapse/assets/30566970/84a0d709-16f2-449f-9af2-52221b5a7f26
=> Resizable Game Window

CollapseLauncher/Classes/ShortcutCreator/ShortcutCreator.cs, CollapseLauncher/Classes/ShortcutCreator/SteamShortcut.cs, CollapseLauncher/Program.cs, CollapseLauncher/XAMLs/MainApp/Pages/HomePage.xaml.cs, CollapseLauncher/XAMLs/MainApp/Pages/SettingsPage.xaml.cs
- Fixes folders not being found if the steamID ended with an 0.
- Adds/improves some logging when searching for valid userdata folders
- Changes target exe/folder to the stub executable/folder
=> [Steam shortcuts] Small fixes 

Hi3Helper.Core/Classes/DiscordPresence/src/Core.cs
Discord will call `CloseHandle` on an already closed named pipe "discord-ipc-0" handle if Discord client was closed before we call `Destroy`.
Only affects debug mode.
=> (Discord RPC) Catch SEHException on Dispose

CollapseLauncher/Classes/ShortcutCreator/SteamShortcut.cs, CollapseLauncher/Classes/ShortcutCreator/SteamShortcutParser.cs
https://gist.github.com/gablm/2a79355026bde51ac4f516d347fa1cd0 has a basic explanation of the ```shortcuts.vdf``` format. Hope it finds its way to anyone trying to decipher this file in the near future.
closes #400
=> Fix parsing for ```LastPlayTime``` in the Steam Shortcuts Parser 

CollapseLauncher.sln.DotSettings, CollapseLauncher/Classes/RegionManagement/RegionManagement.cs, CollapseLauncher/XAMLs/MainApp/MainPage.xaml.cs, CollapseLauncher/XAMLs/MainApp/Pages/SettingsPage.xaml, CollapseLauncher/XAMLs/MainApp/Pages/SettingsPage.xaml.cs, Hi3Helper.Core/Classes/Shared/Region/LauncherConfig.cs, Hi3Helper.Core/Lang/Locale/LangSettingsPage.cs, Hi3Helper.Core/Lang/en_US.json
- Instantly change the region when selected game or region is changed.
- Hide the "Change" button.
- Enabled by default when "Show Region Warning" is disabled
https://github.com/CollapseLauncher/Collapse/assets/28079733/05ede866-d9e7-413e-81ae-f327ad35ccb8
=> Instant Region Change

CollapseLauncher/Classes/Helper/LauncherApiLoader/LauncherApiBase.cs, CollapseLauncher/CollapseLauncher.csproj, CollapseLauncher/XAMLs/MainApp/Pages/UpdatePage.xaml, CollapseLauncher/packages.lock.json, Hi3Helper.Core/Lang/ja_JP.json, Hi3Helper.Core/Lang/zh_CN.json, Hi3Helper.Core/packages.lock.json, InnoSetupHelper/packages.lock.json, README.md
- **[Fix]** Crash on launch when using certain language, by @bagusnl & @shatyuka 
- This due to HoYo does not have response in their API for `es-419` and `pt-br` locales. For background and news area, fallback `es-419` to `es-es` and `pt-br` to `pt-pt`.
- **[Imp]** Adjusted Update page tittle padding, by @shatyuka 
- **[Loc]** Sync localization from Transifex, by localizers <3
Template:
**[New]**
**[Imp]**
**[Fix]**
**[Loc]**
**[Doc]**
=> Preview 1.80.2 Emergency Hotfix Release

CollapseLauncher.sln, CollapseLauncher/Classes/CoCreateInstance.cs, CollapseLauncher/Classes/GameManagement/GameSettings/Genshin/RegistryClass/GeneralData.cs, CollapseLauncher/Classes/Helper/Image/Waifu2X.cs, CollapseLauncher/Classes/Helper/WindowUtility.cs, CollapseLauncher/Classes/InstallManagement/BaseClass/InstallManagerBase.cs, CollapseLauncher/Classes/InstallManagement/StarRail/StarRailInstall.cs, CollapseLauncher/Classes/Interfaces/Class/ProgressBase.cs, CollapseLauncher/Classes/RegistryMonitor/RegistryMonitor.cs, CollapseLauncher/Classes/RepairManagement/Honkai/Check.cs, CollapseLauncher/Classes/RepairManagement/Honkai/Fetch.cs, CollapseLauncher/XAMLs/MainApp/MainPage.xaml.cs, CollapseLauncher/XAMLs/MainApp/TrayIcon.xaml.cs, CollapseLauncher/packages.lock.json, Hi3Helper.Core/Classes/Data/InvokeProp.cs, Hi3Helper.Core/Classes/Data/ScreenData.cs, Hi3Helper.Core/Classes/Logger/LoggerBase.cs, Hi3Helper.Core/Classes/Logger/Type/LoggerConsole.cs, Hi3Helper.Core/Classes/Shared/ClassStruct/Class/GameDataStructure.cs, Hi3Helper.Core/Lang/zh_CN.json, Hi3Helper.Sophon.Test/Hi3Helper.Sophon.Test.csproj, Hi3Helper.Sophon.Test/Hi3Helper.Sophon.Test/Hi3Helper.Sophon.Test.sln, Hi3Helper.Sophon.Test/Program.cs, Hi3Helper.Sophon.Test/Properties/launchSettings.json, README.md
- Overall Status : DONE
-  **[Fix]**: Skip pustaka file if not present, by @neon-nyan 
- **[Imp]**: Add new GI 4.7 field, by @bagusnl 
- **[Fix]**: Used file being called twice, for Hi3, by @neon-nyan 
- **[Fix]**: Stop Windows from opening files sometimes for no reason, by @neon-nyan 
- "File is being used by another process" should be resolved, by @neon-nyan 
- **[Fix]**: Windows 10 client size should be normal now, by @shatyuka 
- **[Fix]**: Remove 1px border offset on Windows 10, by @shatyuka 
- **[Fix]**: Add missing attribute, `SetLastError` to interop calls, by @shatyuka 
- **[New]**: Move `Hi3Helper.Sophon.Test` to its own solution, by @neon-nyan 
- **[Fix]**: Sometimes the console would …
=> [New Mainline Release] 1.80.9 Preview

CollapseLauncher/Classes/GamePropertyVault.cs, CollapseLauncher/Classes/InstallManagement/BaseClass/GameInstallPackage.cs, CollapseLauncher/Classes/InstallManagement/BaseClass/InstallManagerBase.cs, CollapseLauncher/Classes/InstallManagement/Zenless/ZenlessInstall.cs, CollapseLauncher/CollapseLauncher.csproj
- **[New]** ZZZ Pre-download Support, by @neon-nyan 
- **[New]** Bilibili Region Support for ZZZ, by @bagusnl & @neon-nyan  
- **[Imp]** Bring back the old file download behavior to store chunk files as sequential ``.001`` files, by @neon-nyan
This change however, is backward compatible if you still have the hash-based (``.xxxxx``) extension chunks.
- **[Fix]** Random "File is being used by another process" Errors when Downloading, by @neon-nyan 
<details>
```
**[New]**
**[Imp]**
**[Fix]**
**[Loc]**
**[Doc]**
```
</details>
=> Stable 1.80.18 Hotfix Release

CollapseLauncher/Classes/InstallManagement/BaseClass/InstallManagerBase.cs, CollapseLauncher/Classes/InstallManagement/Zenless/ZenlessInstall.cs, CollapseLauncher/CollapseLauncher.csproj, Hi3Helper.Core/Lang/es_419.json, README.md
- **[New]** ZZZ Pre-download Support, by @neon-nyan 
- **[New]** Bilibili Region Support for ZZZ, by @bagusnl & @neon-nyan  
- **[New]** Burst Download Mode, by @neon-nyan 
- This will make download process of multiple files faster by downloading them in parallel.
- NOT recommended for those with slower internet, thus disabled by default.
- As its a very experimental settings, if you want to try, edit the Collapse config file:
- `%AppData%\..\CollapseLauncher\config.ini`, add/modify `IsBurstDownloadModeEnabled` key to "True".
- **[Fix]** Use the Custom Resolution Enforcer for ALL Games, by @bagusnl 
- Practically when you use Custom Res, forces all game to obey the resolution by changing its Window property.
- **[Fix]** Black Bar on top of Image Carousel, by @shatyuka 
- **[Fix]** …
=> [Urgent] Preview 1.81.3 Hotfix Release

CollapseLauncher/Classes/InstallManagement/BaseClass/InstallManagerBase.cs, CollapseLauncher/Classes/InstallManagement/Zenless/ZenlessInstall.cs, CollapseLauncher/CollapseLauncher.csproj
- **[New]** ZZZ Pre-download Support, by @neon-nyan 
- **[New]** Bilibili Region Support for ZZZ, by @bagusnl & @neon-nyan  
- **[Imp]** Bring back the old file download behavior to store chunk files as sequential ``.001`` files, by @neon-nyan
This change however, is backward compatible if you still have the hash-based (``.xxxxx``) extension chunks.
- **[Fix]** Random "File is being used by another process" Errors when Downloading, by @neon-nyan 
- **[Fix]** Potentially skipping HDiff patching and old files removal routine while applying ZZZ Update, by @neon-nyan 
- **[Fix]** ``Hi3Helper.Http`` submodule causing size miscalculation while downloading files, by @neon-nyan 
<details>
```
**[New]**
**[Imp]**
**[Fix]**
**[Loc]**
**[Doc]**
```
</details>
=> [Urgent] Stable 1.80.19 Hotfix Release

.github/ISSUE_TEMPLATE/feature_request.yml
To fix a small typo I saw while creating a feature request issue!
- Bug found caused by PR : 0 (hopefully not by this simple fix)
=> Fix typo in feature_request.yml

CollapseLauncher/Classes/GameManagement/GameSettings/Zenless/FileClass/GeneralData.cs, CollapseLauncher/Classes/GameManagement/GameSettings/Zenless/Settings.cs, CollapseLauncher/Classes/InstallManagement/BaseClass/InstallManagerBase.cs, CollapseLauncher/Classes/RepairManagement/StarRail/Check.cs, CollapseLauncher/CollapseLauncher.csproj, CollapseLauncher/XAMLs/MainApp/MainPage.xaml.cs, CollapseLauncher/XAMLs/MainApp/Pages/CachesPage.xaml, CollapseLauncher/XAMLs/MainApp/Pages/GameSettingsPages/GenshinGameSettingsPage.xaml, CollapseLauncher/XAMLs/MainApp/Pages/GameSettingsPages/HonkaiGameSettingsPage.xaml, CollapseLauncher/XAMLs/MainApp/Pages/GameSettingsPages/StarRailGameSettingsPage.xaml, CollapseLauncher/XAMLs/MainApp/Pages/GameSettingsPages/ZenlessGameSettingsPage.Ext.cs, CollapseLauncher/XAMLs/MainApp/Pages/GameSettingsPages/ZenlessGameSettingsPage.xaml, CollapseLauncher/XAMLs/MainApp/Pages/HomePage.xaml.cs, CollapseLauncher/XAMLs/MainApp/Pages/RepairPage.xaml, CollapseLauncher/XAMLs/MainApp/Pages/SettingsPage.xaml.cs, CollapseLauncher/packages.lock.json, Hi3Helper.Core/Lang/Locale/LangZenlessGameSettingsPage.cs, Hi3Helper.Core/Lang/en_US.json, Hi3Helper.Core/Lang/id_ID.json, Hi3Helper.Core/Lang/zh_CN.json, Hi3Helper.TaskScheduler/Hi3Helper.TaskScheduler.csproj, Hi3Helper.TaskScheduler/packages.lock.json, README.md, appveyor.yml
- **[Fix]** Revert NativeAOT publishing and use regular trimmed builds instead, by @bagusnl 
- This due to several reports about freezing and memory leaks. We will try to evaluate this kind of builds more in the future once .NET 9 is fully released.
- **[Imp]** Add new settings for Zenless Zone Zero, by @bagusnl 
- The setting in English is called "High-Precision Character Animation" but in Indonesian its roughly translated as "Dynamic Character Resolution". I honestly don't know what they are doing LMAO
- **[Fix]** Adjusted Star Rail game repair mechanism, by @neon-nyan 
- **[Fix]** Sophon pre-download showing the wrong size, by @neon-nyan 
- **[Fix]** Plugin update launch errors, by @bagusnl 
- **[Fix]** NullReferenceException when checking for launcher update when it's on the latest, …
=> Preview 1.82.1 Release

CollapseLauncher/Classes/GameManagement/GameVersion/BaseClass/GameVersionBase.cs, CollapseLauncher/Classes/Helper/Database/DBConfig.cs, CollapseLauncher/Classes/Helper/TaskSchedulerHelper.cs, CollapseLauncher/CollapseLauncher.csproj, CollapseLauncher/XAMLs/Invoker/Classes/Migrate.cs, Hi3Helper.Core/Classes/Shared/Region/LauncherConfig.cs, Hi3Helper.Core/Data/IniFile.cs, Hi3Helper.Core/Data/IniValue.cs
- **[Fix]** Fix redundant Ini save-load mechanism and FileNotFoundException upon loading, by @neon-nyan 
This caused the launcher to throw ``FileNotFoundException`` error in the background and causing the region fail to load.
- **[Imp]** Improvement on ``IniValue``, by @neon-nyan 
- Always cache ``IsEmpty`` property and update it only if the ``Value`` property is being set.
- Add missing casting for ``Size`` struct
- Add ``Create()`` static method
- Add ``ToGuid()`` method and cast support
- Add support for creating ``IniValue`` from ``Enum``
- **[Fix]** Avoid double desktop shortcut by using user's Desktop path, by @neon-nyan 
- **[Fix]** Fix wrong casting on implicit IniValue operator for Int32, by @neon-nyan 
----------------
- **[Fix]** Download corruption due to download chunk size …
=> [Urgent] Preview 1.82.7 Hotfix Release

CollapseLauncher/Classes/Helper/StreamUtility.cs, CollapseLauncher/Classes/InstallManagement/BaseClass/InstallManagerBase.cs, CollapseLauncher/Classes/InstallManagement/GameConversionManagement.cs, CollapseLauncher/Classes/Interfaces/Class/ProgressBase.cs, CollapseLauncher/Classes/Interfaces/Class/Structs.cs, CollapseLauncher/Classes/RegionManagement/FallbackCDNUtil.cs, CollapseLauncher/Classes/RepairManagement/BSDiff.cs, CollapseLauncher/Classes/RepairManagement/Genshin/Fetch.cs, CollapseLauncher/Classes/RepairManagement/StarRail/Check.cs, CollapseLauncher/CollapseLauncher.csproj, CollapseLauncher/XAMLs/MainApp/Pages/Dialogs/SimpleDialogs.cs, CollapseLauncher/XAMLs/Updater/Classes/Updater.cs, CollapseLauncher/XAMLs/Updater/UpdaterWindow.xaml.cs, Hi3Helper.Core/Lang/Locale/LangUpdatePage.cs, Hi3Helper.Core/Lang/en_US.json, Hi3Helper.Core/Lang/ja_JP.json, Hi3Helper.Core/Lang/zh_CN.json, README.md
- **[Fix]** ``NullReferenceException`` crash caused by null ``voice_packs`` property, by @neon-nyan
- **[Fix]** Some migration dialog still provides install choices, by @neon-nyan
- **[Fix]** TimeSpan overflow + Number to Percentage and TimeSpan converter refactor, by @neon-nyan and @bagusnl
- **[Fix]** Minor Audio Selection UI bug, by @neon-nyan
- **[Fix]** More ``SharingViolation`` exceptions on ``InstallManagerBase``, by @neon-nyan
- **[Fix]** ``DirectoryNotFoundException`` on HSR's Game Repair -> ``RemoveHashMarkFile()`` method, by @neon-nyan
- **[Fix]** Relative URL for the Velopack packages getting cut-off, by @neon-nyan
<details>
```
**[New]**
**[Imp]**
**[Fix]**
**[Loc]**
**[Doc]**
```
</details>
=> Stable 1.82.10 Hotfix

CollapseLauncher/Classes/InstallManagement/BaseClass/InstallManagerBase.Sophon.cs, CollapseLauncher/Classes/InstallManagement/BaseClass/InstallManagerBase.cs, CollapseLauncher/CollapseLauncher.csproj, CollapseLauncher/XAMLs/MainApp/MainPage.xaml.cs, Hi3Helper.Core/Classes/SentryHelper/SentryHelper.cs, Hi3Helper.Core/Lang/Locale/LangDialogs.cs, Hi3Helper.Core/Lang/en_US.json, README.md
- **[Fix]** Failure when installing sophon, by @neon-nyan 
- neon forgor to put the variable into the right line
- **[Fix]** Disk space recognition when resuming game install with
sophon, by @neon-nyan
- neon forgor to return the right value
- **[Fix]** Game update with sophon failing if its updating from a
version that is too old, by @neon-nyan
- neon too eepy and forgor to check if the manifest exist for those
older game version
- if the game is too old then fallback to use install method and replace
any assets that is not matching with the target version.
- **[Fix]** `EnumFailedVersion` errors when installing games and (super
rarely) in early launch, by @bagusnl
- **[Imp]** Use Attachment instead of breadcrumbs for LoadedModules
reporting in Sentry, by @bagusnl
=> Stable 1.82.12 Emergency Hotfix

CollapseLauncher/Classes/Helper/WindowUtility.cs, CollapseLauncher/Classes/Interfaces/Class/ProgressBase.cs
Implementation of proposal #502, show taskbar progress in these scenarios:
- Game Downloads/Updates
- Game Repair
- Cache Update
- Game Pre-Download
=> Show current progress in taskbar

CollapseLauncher/Classes/Helper/WindowUtility.cs, CollapseLauncher/XAMLs/MainApp/MainPage.xaml.cs, CollapseLauncher/XAMLs/MainApp/MainWindow.xaml.cs, CollapseLauncher/XAMLs/MainApp/Pages/CachesPage.xaml.cs, CollapseLauncher/XAMLs/MainApp/Pages/Dialogs/SimpleDialogs.cs, CollapseLauncher/XAMLs/MainApp/Pages/HomePage.xaml.cs, CollapseLauncher/XAMLs/MainApp/Pages/RepairPage.xaml.cs, Hi3Helper.Core/Lang/Locale/LangDialogs.cs, Hi3Helper.Core/Lang/en_US.json
Show dialog confirming user before exiting app while critical process is happening
Close #671 
Currently implemented in:
- Game Install
- Game Update
- Cache Update
- Game Repair
- Bug found caused by PR : 0
- Bug found when making this PR, unrelated to the PR itself
When closing app while some UI progress is happening, there is a chance that it throws bunch of errors on XAML thread before it exit
<details>
```
**[New]**
**[Imp]**
**[Fix]**
**[Loc]**
**[Doc]**
```
</details>
=> Prevent closing app while doing critical process

.github/workflows/build.yml, .github/workflows/qodana-scan-pr.yml, .github/workflows/qodana-scan.yml, .github/workflows/vt-scan-releases.yml, CollapseLauncher/Classes/GameManagement/GamePlaytime/Playtime.cs, CollapseLauncher/Classes/InstallManagement/Base/InstallManagerBase.cs, CollapseLauncher/Classes/Interfaces/Class/ProgressBase.cs, CollapseLauncher/Classes/RepairManagement/Genshin/Check.cs, CollapseLauncher/Classes/RepairManagement/Genshin/Fetch.cs, CollapseLauncher/CollapseLauncher.csproj, Hi3Helper.Core/Lang/id_ID.json, Hi3Helper.Core/Lang/ja_JP.json, README.md
- **[Fix]** Launcher crashing when the main game thread unexpectedly closes, by @neon-nyan 
- **[Fix]** Taskbar progress not reset after game install/update, by @shatyuka 
- **[Fix]** Ensures temporary files availability, by @neon-nyan 
- **[Fix]** 7z COMException errors, by @neon-nyan 
- **[Fix]** Genshin's repair missing a few files, by @neon-nyan 
<details>
```
**[New]**
**[Imp]**
**[Fix]**
**[Loc]**
**[Doc]**
```
</details>
=> Preview 1.82.18 Hotfix

CollapseLauncher/Classes/GameManagement/GameSettings/Zenless/Enums.cs, CollapseLauncher/Classes/GameManagement/GameSettings/Zenless/FileClass/GeneralData.cs, CollapseLauncher/XAMLs/MainApp/Pages/GameSettingsPages/ZenlessGameSettingsPage.Ext.cs, CollapseLauncher/XAMLs/MainApp/Pages/GameSettingsPages/ZenlessGameSettingsPage.xaml, Hi3Helper.Core/Lang/Locale/LangZenlessGameSettingsPage.cs, Hi3Helper.Core/Lang/en_US.json
AKA Anisotropic Filtering, but kept the in-game name for clarity. All presets seem to not change the value, keeping it at x8.
Update ZZZ GSP so that it is in parity with the in-game options.
- Overall Status : Done ✅ 
- Commits : Done ✅ 
- Synced to base (Collapse:main) : Yes ✅ 
- Build status : OK ✅ 
-  **[New]** Added new dropdown menu for Anisotropic Sampling option (x1, x2, x4, x8, x16), with x8 as default
-   **[Loc]** Added new i18n string for option
=> Add Anisotropic Sampling option to ZZZ GSP

CollapseLauncher/Classes/GamePresetProperty.cs, CollapseLauncher/Classes/Helper/Metadata/PresetConfig.cs, CollapseLauncher/Classes/InstallManagement/Base/InstallManagerBase.Sophon.cs, CollapseLauncher/Classes/InstallManagement/Base/InstallManagerBase.SophonPatch.cs, CollapseLauncher/Classes/InstallManagement/Base/InstallManagerBase.cs, CollapseLauncher/Classes/Interfaces/Class/GamePropertyBase.cs, CollapseLauncher/CollapseLauncher.csproj, CollapseLauncher/packages.lock.json
This PR implements a new update mode for Sophon which is currently in A/B Testing phase for the official HoYoPlay launcher.
Sophon Patch Update mode brings a much improved download pipeline and update efficiency as this method involves not only Copy-Over method, but also Patch-Over method via HDiffPatch.
This results a much smaller download footprint compared to the old Copy-Over only method. As an example of this, we compared Genshin Impact 5.4.0 -> 5.5.0 update between the Old and New method.
The old method requires 15.97 GB of data to download. Meanwhile, the new method only requires 5.92 GB of data to download, which is **62.9%** of size reduction over old method.
Note: In this test, we installed two VOs: en-us + ja-jp
- Synced to base …
=> [Imp] Implement new Sophon Patch Mode

CollapseLauncher/Classes/GameManagement/Versioning/GameVersionBase.GameState.cs, CollapseLauncher/Classes/Helper/LauncherApiLoader/HoYoPlay/HoYoPlayLauncherApiLoader.cs, CollapseLauncher/Classes/Helper/LauncherApiLoader/HoYoPlay/HoYoPlayLauncherGameInfo.cs, CollapseLauncher/Classes/Helper/LauncherApiLoader/ILauncherApi.cs, CollapseLauncher/Classes/Helper/LauncherApiLoader/LauncherApiBase.cs, CollapseLauncher/Classes/Helper/Metadata/PresetConfig.cs, CollapseLauncher/Classes/InstallManagement/Base/InstallManagerBase.Sophon.cs, CollapseLauncher/Classes/InstallManagement/Genshin/GenshinInstall.cs, CollapseLauncher/Classes/Interfaces/IGameVersionCheck.cs
As per Genshin Impact 5.6.0 preload today, miHoYo just removed Zip packages on HoYoPlay API. This caused our launcher unable to detect or determine update state due to the main dependencies to Zip packages only.
This PR fixes the issue by checking if Zip is unavailable, then tell the GameVersionManager to fallback by forcefully redirect the install/update/preload methods to Sophon mode. This PR also avoid the same issue if HoYo might remove the Zip packages to other games in the future.
- Bug found caused by PR : -
=> [EMERGENCY HOTFIX] Forcefully Redirect to Sophon if Zip Method is Unavailable

CollapseLauncher/Classes/CachesManagement/Honkai/Fetch.cs, CollapseLauncher/Classes/GameManagement/Versioning/GameVersionBase.GameState.cs, CollapseLauncher/Classes/GamePresetProperty.cs, CollapseLauncher/Classes/Helper/Hash.FileStream.cs, CollapseLauncher/Classes/Helper/LauncherApiLoader/HoYoPlay/HoYoPlayLauncherApiLoader.cs, CollapseLauncher/Classes/Helper/LauncherApiLoader/HoYoPlay/HoYoPlayLauncherGameInfo.cs, CollapseLauncher/Classes/Helper/LauncherApiLoader/ILauncherApi.cs, CollapseLauncher/Classes/Helper/LauncherApiLoader/LauncherApiBase.cs, CollapseLauncher/Classes/Helper/Metadata/PresetConfig.cs, CollapseLauncher/Classes/InstallManagement/Base/InstallManagerBase.Sophon.cs, CollapseLauncher/Classes/InstallManagement/Base/InstallManagerBase.SophonPatch.cs, CollapseLauncher/Classes/InstallManagement/Base/InstallManagerBase.cs, CollapseLauncher/Classes/InstallManagement/Genshin/GenshinInstall.cs, CollapseLauncher/Classes/Interfaces/Class/GamePropertyBase.cs, CollapseLauncher/Classes/Interfaces/Class/ProgressBase.cs, CollapseLauncher/Classes/Interfaces/IGameVersionCheck.cs, CollapseLauncher/Classes/RepairManagement/Genshin/Fetch.cs, CollapseLauncher/Classes/RepairManagement/Honkai/Check.cs, CollapseLauncher/Classes/RepairManagement/Honkai/Fetch.cs, CollapseLauncher/Classes/RepairManagement/Honkai/HonkaiRepair.cs, CollapseLauncher/Classes/RepairManagement/Honkai/Repair.cs, CollapseLauncher/CollapseLauncher.csproj, CollapseLauncher/XAMLs/MainApp/Pages/HomePage.GameLauncher.cs, CollapseLauncher/packages.lock.json, Hi3Helper.Core/packages.lock.json
This main change was to bring back Game Repair and Delta-Patch support for Stable due to breaking changes that were introduced by HoYo in Honkai Impact 3rd v8.2 update.
This hotfix was backported from ``main`` branch.
This changes implements a new update mode for Sophon which is currently in A/B Testing phase for the official HoYoPlay launcher.
Sophon Patch Update mode brings a much improved download pipeline and update efficiency as this method involves not only Copy-Over method, but also Patch-Over method via HDiffPatch.
This results a much smaller download footprint compared to the old Copy-Over only method. As an example of this, we compared Genshin Impact 5.4.0 -> 5.5.0 update between the Old and New method.
As per Genshin Impact 5.6.0 preload today, miHoYo just removed Zip packages …
=> [EMERGENCY HOTFIX] Backport Hotfixes to Stable (1.82.22)

CollapseLauncher/Classes/Helper/WindowUtility.cs, CollapseLauncher/Program.cs, CollapseLauncher/XAMLs/MainApp/MainWindow.xaml.cs, CollapseLauncher/XAMLs/MainApp/Pages/Dialogs/SimpleDialogs.cs, CollapseLauncher/packages.lock.json, Hi3Helper.Core/Lang/Locale/LangDialogs.cs, Hi3Helper.Core/Lang/en_US.json
Preventing Windows from ending it's ~~life~~ session when Collapse is running critical task. Should prevent accidental shutting down when Collapse is installing/updating/repairing games.
Thanks @neon-nyan for the screenshot.
P.S. This doesn't work when you run Collapse inside a debugger, because the debugger will kill its target process when Windows is ending the session.
- Bug found caused by PR : 0
<details>
```
**[New]**
**[Imp]**
**[Fix]**
**[Loc]**
**[Doc]**
```
</details>
=> [Feature] Prevent Windows Log off/Restart/Shutdown when running critical task

CollapseLauncher/XAMLs/MainApp/Pages/SettingsPage.xaml, CollapseLauncher/XAMLs/MainApp/Pages/SettingsPage.xaml.cs, CollapseLauncher/packages.lock.json, Hi3Helper.Core/Lang/Locale/LangSettingsPage.cs, Hi3Helper.Core/Lang/en_US.json
Adds a debug UI element in the settings page to allow for spawning custom dialogs for testing purposes.
You can search for the dialog box that you want using the `AutoSuggestionBox` field. Please note that currently, only dialogs implemented in the `SimpleDialogs` class are supported, but we could add more classes in the future if we'd like to do that.
Some dialogs require specific parameters, those have been made to spawn a dialog box before spawning the selected dialog, so that you can manually input them and pass them as parameters.
https://github.com/user-attachments/assets/42ee469c-38f4-4b18-a547-29c37155f597
- Bug found caused by PR : 0
=> Adds debug dialog spawning UI in settings

CollapseLauncher/Classes/Extension/VelopackLocatorExtension.cs, CollapseLauncher/Classes/Properties/ArgumentParser.cs, CollapseLauncher/CollapseLauncher.csproj, CollapseLauncher/Program.cs, CollapseLauncher/packages.lock.json, Hi3Helper.Core/Classes/Logger/Type/LoggerConsole.cs
Update System.CommandLine to beta 5
What works:
- `open`, though it doesn't state the error or notice when the argument input is invalid.
- Cc @gablm  
- `tray`
- `generatevelopackmetadata`
- Crashing : Yes
- Bug found caused by PR : 1
- Suboption doesn't state the error or notice when the argument input is invalid.
<details>
```
**[New]**
**[Imp]**
**[Fix]**
**[Loc]**
**[Doc]**
```
</details>
=> Update System.CommandLine dependency
